{% set version = '0.15.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-intervals
  version: {{ version|replace("-", "_") }}

source:
  fn: intervals_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/intervals_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/intervals/intervals_{{ version }}.tar.gz
  sha256: 9a8b3854300f2055e1492c71932cc808b02feac8c4d3dbf6cba1c7dbd09f4ae4

build:
  merge_build_host: True  # [win]
  number: 1003
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('intervals')"           # [not win]
    - "\"%R%\" -e \"library('intervals')\""  # [win]

about:
  home: http://github.com/edzer/intervals
  license: Artistic-2.0
  summary: Tools for working with and comparing sets of points and intervals.
  license_family: OTHER

extra:
  recipe-maintainers:
    - conda-forge/r
    - jsignell
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
