{% set version = "0.15.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-intervals
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/intervals_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/intervals/intervals_{{ version }}.tar.gz
  sha256: 11907be2c47ee4f6359055113dc0dab9ba2c35fbc743c2d52fd1ba1006c7ce5c

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('intervals')"           # [not win]
    - "\"%R%\" -e \"library('intervals')\""  # [win]

about:
  home: http://github.com/edzer/intervals
  license: Artistic-2.0
  summary: Tools for working with and comparing sets of points and intervals.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
    - jsignell

# Package: intervals
# Version: 0.15.2
# Type: Package
# Title: Tools for Working with Points and Intervals
# Author: Richard Bourgon <bourgon.richard@gene.com>
# Maintainer: Edzer Pebesma <edzer.pebesma@uni-muenster.de>
# Depends: R (>= 2.9.0)
# Imports: utils, graphics, methods
# Description: Tools for working with and comparing sets of points and intervals.
# License: Artistic-2.0
# LazyLoad: yes
# URL: http://github.com/edzer/intervals
# NeedsCompilation: yes
# Packaged: 2020-04-04 09:41:39 UTC; edzer
# Repository: CRAN
# Date/Publication: 2020-04-04 10:00:02 UTC
