{% set version = '0.15.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-intervals
  version: {{ version|replace("-", "_") }}

source:
  fn: intervals_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/intervals_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/intervals/intervals_{{ version }}.tar.gz
  sha256: 9a8b3854300f2055e1492c71932cc808b02feac8c4d3dbf6cba1c7dbd09f4ae4

build:
  merge_build_host: True  # [win]
  number: 2
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:

    - $R -e "library('intervals')"  # [not win]
    - "\"%R%\" -e \"library('intervals')\""  # [win]

about:
  home: http://github.com/edzer/intervals
  license: Artistic-2.0
  summary: Tools for working with and comparing sets of points and intervals.
  license_family: OTHER

extra:
  recipe-maintainers:
    - dpryan79
    - jsignell
