travis:
  secure:
    BINSTAR_TOKEN: ZncW5Ml8qHd0HtjPn2QjM0YW8S9B16ODKauXqpYB2bp0sCHp78ylASJGpDtQE66axf3mJpKOOgeolK29lWLQHshAQSjbYxvnjhZf/tN+JxU1AUkC8OH7wFh5syM+zdQE41XMHIhurFHKubFxS8DN1DW9binkVN68CEmYzh6xDvBs7VS5va8d8JRSkNIb1pwzq8JHUr+/Qn06y+WknSHq+1CP+YRr4bTABnNR1AvN+jZqkcRJBCF7XJ44aWT9UFEWmlbUFd0Wgi/wBClNAmPVbVllPU7qChJV6vPgMl7IKB5KcO7iU36L+0MaThPtuDs3/WOZ+kdRHFy4EgMENTYu+0PuFU74klSYVPfCKUpCVQoHlYaW03tHuSrXgKxNrngxuhHUETk5yL3IZUARKi3M6m90UdnKlodmVT8iNYFotJIrkbc6iRZV+5xGitpRvfYclt/7ClKEq7W8SnfQKd73Wnz+tLUMwIogXWqxXM+JaJ5zRutQ9kxJg60fZS9J7FfxIH8rp8lUnKgn/YMi6zzN6mcMnYyrpNu4rEvIgnbdoqgtrehOEC+rCEW3lohPFAD7eO6KFdtxqbqKP2owV6YqAFdYwsuPoMCdRehmpFsGSNaEgOdVGJCMRLOsQpqnlyu9K4E2dMJSElcgwyvO7oUhZmDcb9+CYBOvSYeSqj7FQrc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
